all:
	g++ -std=c++11 -O3 -g -Wall -fmessage-length=0 -o nogo nogo.cpp -lpthread
mcts:
	g++ -std=c++11 -O3 -g -Wall -fmessage-length=0 -o nogo_mcts nogo.cpp -lpthread
2:
	g++ -std=c++11 -O3 -g -Wall -fmessage-length=0 -o nogo2 nogo.cpp -lpthread
test:
	g++ -std=c++11 -O3 -g -Wall -fmessage-length=0 -o nogo_test nogo.cpp -lpthread
origin:
	g++ -std=c++11 -O3 -g -Wall -fmessage-length=0 -o nogo_origin nogo.cpp -lpthread
clean:
	rm nogo