all:
	g++ -std=c++11 -O3 -g -Wall -fmessage-length=0 -o nogo nogo.cpp -lpthread
1:
	g++ -std=c++11 -O3 -g -Wall -fmessage-length=0 -o nogo1 nogo.cpp -lpthread
2:
	g++ -std=c++11 -O3 -g -Wall -fmessage-length=0 -o nogo2 nogo.cpp -lpthread
gg:
	g++ -std=c++11 -O3 -g -Wall -fmessage-length=0 -o nogo2 nogo.cpp -lpthread -ggdb
clean:
	rm nogo